Output magi.gif

Set Shell zsh
Set FontSize 16
Set Width 1200
Set Height 800

Sleep 2s
Type "magi"
Enter

Sleep 4s
Type "jjjj"

Sleep 2s
Tab

Sleep 2s
Type "?"

Sleep 4s
Type "l"

Sleep 2s
Type "a"

Sleep 500ms
Ctrl+D

Sleep 500ms
Ctrl+D

Sleep 500ms
Ctrl+D

Sleep 1s
Type "gg"

Sleep 1s
Type "q"

Sleep 1s
Type "S"

Sleep 2s
Type "c"

Sleep 2s
Type "c"

Sleep 2s
Type "IShow off Magi!!!"
Sleep 2s
Escape
Type ":wq"
Enter

Sleep 4s
